language: node_js
node_js:
- 6
install:
- npm install
- npm link
deploy:
  skip_cleanup: true
  provider: npm
  email: bradwoo8621@gmail.com
  api_key:
    secure: DLWaVF54bDIAscoqST/UXCS8XC3YZUlmVCo67OaX4EZfij6p/4FGaSTpU4bbcv5aGlfNAdSLXefcIxYsZJPMU3xlQmZwwBfSMhvsEtDQFjWks0kQeFSBHhOcJjaX+nKd0EdZs76i3opeaSImSasnT2zcG/olc+gZu9NbQFcnwup+BLasQHXcIIFBBH9Nmdp00Ze8sV3KuCUNuDCm+4ObNFuCdO8wuYSI6D+mXRnzHjPv53W0ySVL2LP4EyNeiKaAQUhHmlpYHb0kfl7vlF/Occ8Ls2f2QMVNjmHeEyP71mCxQFlQipR18s5gWTqxquUs3dMV0m5gqZTOH/YboaUp6YAzq9TKEcMYMSH3wY3Vy81PdcaHRE6muxYKV30qkCn8Dk8mg565UjeCrbO0i3sZSixh98kfPRXqNAp9UuAFmtFZVfU+pv3vZAEluEMsM6HgA+E9pZ0cxDDhtymlVf32/TIJwafMvXC/6pLlGSPUAsq/H8aMh1VQqN7Sxcxj4bFceoKdNW9/nzMM5jz6nRqj8OinHEifweRdirlM/YMAjEOWFY7sj1ocACF8eJjIApQNG0z+T1PIz3sO9DNpU9PT/6+Rk0BTrliSeWxhBsWwohBOW32rSyRuGjjMJRQ27JF7p1kTbqks7a1wJJyL/g3nubvbW64aCQOHzZruyEXAYbw=
  on:
    tags: true
